namespace: "fortinet"
name: "fortimanager"
version: "2.11.0"
readme: "README.md"
authors:
    - "Xinwei Du (@dux-fortinet)"
    - "Xing Li (@lix-fortinet)"
    - "Xue Jie (@JieX19)"
    - "Link Zheng (@chillancezen)"
    - "Hongbin Lu (@fgtdev-hblu)"
    - "Frank Shen (@frankshen01)"
description: "The FortiManager Ansible Collection."
license:
    - "GPL-3.0-or-later"
tags:
    - fortinet
    - fortimanager
    - networking
    - security
    - cloud
dependencies: { "ansible.netcommon": "*" }
repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection"
documentation: "https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/latest"
homepage: "https://fortinet.com"
issues: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues"
build_ignore:
    - ".github"
